version: '3.7'
services:
  oracle:
    image: gvenzl/oracle-xe:18.4.0-slim
    environment:
      - ORACLE_RANDOM_PASSWORD=true
      - APP_USER=fpabonnent_unit
      - APP_USER_PASSWORD=fpabonnent_unit
      - ORACLE_DATABASE=XEPDB2
    shm_size: 2gb
    ports:
      - "1521:1521"
    volumes:
      - ./oracle-init:/docker-entrypoint-initdb.d/
    container_name: oraclefpabonnent
