version: '3.7'
services:
  oracle:
    image: ghcr.io/navikt/oracle-foreldrepenger:11
    container_name: oraclefpabonnent
    shm_size: 2gb
    ports:
      - 1521:1521
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d/
