version: 2
registries: # Define access for private registries
  fp-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles
    username: x-access-token
    password: ${{ secrets.PAT }}

updates:
- package-ecosystem: "maven"
  directory: "/"
  registries: # Allow version updates for dependencies in this registry
    - fp-felles
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: io.astefanutti.metrics.cdi:metrics-cdi
    versions:
    - "> 1.4.0, < 2"
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - ">= 5.a, <= 8"
  - dependency-name: org.flywaydb:flyway-maven-plugin
    versions:
    - ">= 5.a, <= 8"
  - dependency-name: org.ow2.asm:asm
    versions:
    - ">= 8.a, <= 9"
  - dependency-name: org.ow2.asm:asm-analysis
    versions:
    - ">= 8.a, <= 9"
  - dependency-name: org.ow2.asm:asm-tree
    versions:
    - ">= 8.a, <= 9"
