apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fpabonnent
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  team: teamforeldrepenger
  liveness:
    path: /fpabonnent/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /fpabonnent/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  preStopHookPath: /fpabonnent/internal/health/preStop
  prometheus:
    enabled: true
    path: /fpabonnent/internal/metrics/prometheus
  resources:
    limits:
      cpu: "2000m"
      memory: "2048Mi"
    requests:
      cpu: "600m"
      memory: "1024Mi"
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  kafka:
    pool: {{kafkaPool}}
  vault:
    enabled: true
    paths:
    - kvPath: {{oraclecredskv}}
      mountPath: /var/run/secrets/nais.io/defaultDS
    - kvPath: {{oracleconfigkv}}
      mountPath: /var/run/secrets/nais.io/defaultDSconfig
    - kvPath: {{serviceuserkv}}
      mountPath: /var/run/secrets/nais.io/serviceuser/
    - kvPath: /apikey/appdynamics/{{environment}}
      mountPath: /var/run/secrets/nais.io/appdynamics
  env:
{{#each env}}
   - name: {{@key}}
     value: "{{this}}"
{{/each}}
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  {{#if AZURE_IAC_RULES}}
  accessPolicy:
      inbound:
        rules:
        {{#each AZURE_IAC_RULES}}
           - application: {{app}}
             namespace: {{namespace}}
             cluster: {{cluster}}
             {{#if scopes}}
             permissions:
               scopes:
               {{#each scopes}}
               - "{{this}}"
               {{/each}}
             {{/if}}
   {{/each}}
  {{/if}}
