insert into KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE, GYLDIG_FOM, GYLDIG_TOM)
values (SEQ_KODELISTE.NEXTVAL, 'HENDELSE_TYPE', 'DOEDFOEDSELOPPRETTET', 'Dødfødsel opprettet', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
insert into KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
values (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'HENDELSE_TYPE', 'DOEDFOEDSELOPPRETTET', 'NB', 'Dødfødsel opprettet');
