CREATE INDEX IDX_INPUT_FEED_KODE on INNGAAENDE_HENDELSE (INPUT_FEED_KODE);
CREATE INDEX IDX_KODELISTE_6 on KODELISTE(KODEVERK);
CREATE INDEX IDX_KONFIG_VERDI_KODE_6 on KONFIG_VERDI_KODE(KONFIG_TYPE);
CREATE INDEX IDX_KONFIG_VERDI_KODE_7 on KONFIG_VERDI_KODE(KONFIG_GRUPPE);
CREATE INDEX IDX_PROSESS_TASK_2 ON PROSESS_TASK(task_type);