INSERT INTO PROSESS_TASK_FEILHAND (KODE, NAVN, BESKRIVELSE, OPPRETTET_AV, OPPRETTET_TID)
VALUES ('DEFAULT', 'Eksponentiell back-off med tak', NULL, 'VL', to_timestamp('31.01.2018', 'DD.MM.RRRR'));

INSERT INTO PROSESS_TASK_TYPE (KODE, NAVN, FEIL_MAKS_FORSOEK, FEIL_SEK_MELLOM_FORSOEK, FEILHANDTERING_ALGORITME, BESKRIVELSE, OPPRETTET_AV, OPPRETTET_TID)
VALUES ('hendelser.grovsorter', 'Utfører grovsortering av hendelser', '3', '30', 'DEFAULT', NULL, 'VL', to_timestamp('31.01.2018', 'DD.MM.RRRR'));

INSERT INTO PROSESS_TASK_TYPE (KODE, NAVN, FEIL_MAKS_FORSOEK, FEIL_SEK_MELLOM_FORSOEK, FEILHANDTERING_ALGORITME, BESKRIVELSE, OPPRETTET_AV, OPPRETTET_TID)
VALUES ('hendelser.sendHendelse', 'Sender hendelse til vedtaksløsning', '3', '30', 'DEFAULT', NULL, 'VL', to_timestamp('31.01.2018', 'DD.MM.RRRR'));