name: Build, push, and deploy

on:
  push:
    branches:
      - master
env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  ORACLE_IMAGE: docker.pkg.github.com/navikt/vtp/foreldrepenger-oracle
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpabonnent
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut kode
        uses: actions/checkout@v2
      - run:  git fetch --prune --unshallow

      - name: Cache maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Hent tag
        run: echo "::set-env name=TAG::$(date "+%Y.%m.%d")-$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Hent og start Oracle image
        id: oracle
        shell: bash
        run: |
          echo  $GITHUB_TOKEN | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          echo "Henter og starter Oracle image $ORACLE_IMAGE"
          docker-compose -f oracle/docker-compose.yml pull
          rm -f nohup.out
          docker-compose -f oracle/docker-compose.yml up oracle >nohup.out 2>&1 &
          sh -c 'tail -n +0 -f nohup.out | { sed "/Disconnected/q" && kill $$; }' || true

      - name: Kompiler
        run: |
          echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG"
          mvn test -e --batch-mode --settings .github/workflows/.m2/settings.xml
          ls -l migreringer/target/classes/db/migration/defaultDS/V4_0__baseline.sql
          cp migreringer/src/main/resources/db/V4_0__baseline.sql.orig  migreringer/target/classes/db/migration/defaultDS/V4_0__baseline.sql
          mvn install -Dmaven.test.skip=false  -e --batch-mode --settings .github/workflows/.m2/settings.xml
          ls -l migreringer/target/classes/db/migration/defaultDS/V4_0__baseline.sql

        env:
          TZ: Europe/Oslo
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.NOTIFICATION }}
          SONAR: ${{ secrets.SONAR }}

      - name: Bygg, tag og push Docker image
        run: |
          docker build  --tag $IMAGE .
          echo  $GITHUB_TOKEN | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push $IMAGE_BASE

      - name: Opprett deployment issue
        if: success()
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: createdeployissue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Bygg av ${{ env.TAG }}
          body: |
            Kommenter med <b>/promote env namespace</b>, hvor <b>env</b> er et gyldig clusternavn og <b>namespace</b> et eksisterende namespace i det clusteret.
            <table>
            <tr><th>Cluster</th><th>Namespace</th></tr>
            <tr><td>dev-fss</td><td>q1, q0</td></tr>
            <tr><td>prod-fss</td><td>default</td></tr>
            </table>

      - name: Trigg deploy til Q1
        if: success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          issue-number: ${{ steps.createdeployissue.outputs.number }}
          body: /promote dev-fss q1

