name: Build PR or branch

on:
  pull_request:
    branches:
      - master
env:
  ORACLE_IMAGE: docker.pkg.github.com/navikt/fpsak-autotest/oracle-flattened
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_ACCESS_TOKEN: ${{ secrets.NOTIFICATION }}
  TZ: "Europe/Oslo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut kode
        uses: actions/checkout@v2
      - run:  git fetch --prune --unshallow

      - name: Cache maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Image-cache
        uses: actions/cache@v2
        with:
          path: oracle.tar
          key: image-cache-${{ runner.os }}

      - if: steps.image-cache.outputs.cache-hit != 'true'
        run: |
          echo  $GH_ACCESS_TOKEN | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          docker-compose -f oracle/docker-compose.yml pull oracle
          docker save docker.pkg.github.com/navikt/fpsak-autotest/oracle-flattened > oracle.tar

      - if: steps.image-cache.outputs.cache-hit == 'true'
        run: docker load < oracle.tar

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.15

      - name: Hent og start Oracle image
        id: oracle
        shell: bash
        run: |
          echo  $GH_ACCESS_TOKEN | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          echo "Henter og starter Oracle image $ORACLE_IMAGE"
          rm -f nohup.out
          docker-compose -f oracle/docker-compose.yml up oracle >nohup.out 2>&1 &
          sh -c 'tail -n +0 -f nohup.out | { sed "/Disconnected/q" && kill $$; }' || true

      - name: Kompiler
        run: mvn --quiet clean install --batch-mode --settings .github/workflows/.m2/settings.xml
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.NOTIFICATION }}
